# Generated by Django 5.2.13 on 2026-04-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_allow_comments_post_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DeepAI Blog', max_length=120)),
                ('site_tagline', models.CharField(default='个人技术博客与 AI 日报', max_length=180)),
                ('brand_text', models.CharField(default='DeepAI Blog', max_length=120)),
                ('admin_link_text', models.CharField(default='管理后台', max_length=40)),
                ('meta_description_default', models.CharField(default='个人技术博客与 AI 日报', max_length=320)),
                ('meta_keywords_default', models.CharField(default='ai,blog,django', max_length=255)),
                ('profile_name', models.CharField(default='Yuxia', max_length=80)),
                ('profile_role', models.CharField(default='AI Engineer / Builder', max_length=120)),
                ('profile_description', models.CharField(default='记录 AI、编程、自动化和个人产品实践。', max_length=255)),
                ('home_hero_title', models.CharField(default='个人技术博客 + AI 日报', max_length=255)),
                ('home_hero_subtitle', models.CharField(default='分享开发经验、产品实验和 AI 领域一线动态。', max_length=255)),
                ('home_posts_title', models.CharField(default='最新文章', max_length=80)),
                ('home_posts_more_text', models.CharField(default='查看全部', max_length=40)),
                ('home_posts_empty_text', models.CharField(default='还没有发布文章。', max_length=80)),
                ('home_digest_title', models.CharField(default='最新日报', max_length=80)),
                ('home_digest_more_text', models.CharField(default='查看全部', max_length=40)),
                ('home_digest_empty_text', models.CharField(default='还没有发布日报。', max_length=80)),
                ('posts_title', models.CharField(default='文章', max_length=80)),
                ('posts_hint', models.CharField(default='技术实践、开发总结与项目复盘', max_length=180)),
                ('posts_empty_text', models.CharField(default='暂无内容。', max_length=80)),
                ('digest_title', models.CharField(default='AI 日报', max_length=80)),
                ('digest_hint', models.CharField(default='每日 AI 新闻与关键信息速览', max_length=180)),
                ('digest_empty_text', models.CharField(default='暂无内容。', max_length=80)),
                ('tags_title', models.CharField(default='标签', max_length=80)),
                ('tags_hint', models.CharField(default='按主题快速浏览内容', max_length=180)),
                ('tags_empty_text', models.CharField(default='暂无标签。', max_length=80)),
                ('archives_title', models.CharField(default='归档', max_length=80)),
                ('archives_empty_text', models.CharField(default='暂无归档内容。', max_length=80)),
                ('search_title', models.CharField(default='Search', max_length=80)),
                ('search_hint', models.CharField(default='Search any article ...', max_length=180)),
                ('search_placeholder', models.CharField(default='输入标题、摘要或正文关键词', max_length=120)),
                ('search_button_text', models.CharField(default='搜索', max_length=30)),
                ('search_empty_text', models.CharField(default='没有找到匹配内容。', max_length=80)),
                ('about_title', models.CharField(default='关于我', max_length=80)),
                ('about_subtitle', models.CharField(default='专注 AI 应用开发、自动化工作流和独立产品构建。', max_length=180)),
                ('about_body_1', models.CharField(default='这个博客用于记录开发实践、项目反思和 AI 领域的新动态。', max_length=255)),
                ('about_body_2', models.CharField(default='如果你想交流合作，欢迎通过 Email 联系。', max_length=255)),
                ('comments_title', models.CharField(default='评论', max_length=40)),
                ('comments_empty_text', models.CharField(default='还没有评论，欢迎来抢沙发。', max_length=120)),
                ('comments_submit_text', models.CharField(default='提交评论（需审核）', max_length=80)),
                ('comments_closed_text', models.CharField(default='该文章已关闭评论。', max_length=80)),
                ('footer_left_text', models.CharField(default='© {year} DeepAI Blog', max_length=120)),
                ('footer_right_text', models.CharField(default='Built with Django', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Setting',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('open_in_new_tab', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
