# Generated by Django 5.2.13 on 2026-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_navigationitem_sitesetting_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '导航项', 'verbose_name_plural': '导航项'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': '站点配置', 'verbose_name_plural': '站点配置'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '社交链接', 'verbose_name_plural': '社交链接'},
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='label',
            field=models.CharField(max_length=40, verbose_name='导航文案'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='新窗口打开'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(max_length=255, verbose_name='导航链接'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_body_1',
            field=models.CharField(default='这个博客用于记录开发实践、项目反思和 AI 领域的新动态。', max_length=255, verbose_name='关于页正文段落一'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_body_2',
            field=models.CharField(default='如果你想交流合作，欢迎通过 Email 联系。', max_length=255, verbose_name='关于页正文段落二'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_subtitle',
            field=models.CharField(default='专注 AI 应用开发、自动化工作流和独立产品构建。', max_length=180, verbose_name='关于页副标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_title',
            field=models.CharField(default='关于我', max_length=80, verbose_name='关于页标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='admin_link_text',
            field=models.CharField(default='管理后台', max_length=40, verbose_name='后台入口文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='archives_empty_text',
            field=models.CharField(default='暂无归档内容。', max_length=80, verbose_name='归档页空状态文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='archives_title',
            field=models.CharField(default='归档', max_length=80, verbose_name='归档页标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='brand_text',
            field=models.CharField(default='DeepAI Blog', max_length=120, verbose_name='顶部品牌文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='comments_closed_text',
            field=models.CharField(default='该文章已关闭评论。', max_length=80, verbose_name='评论关闭提示文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='comments_empty_text',
            field=models.CharField(default='还没有评论，欢迎来抢沙发。', max_length=120, verbose_name='评论区空状态文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='comments_submit_text',
            field=models.CharField(default='提交评论（需审核）', max_length=80, verbose_name='评论提交按钮文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='comments_title',
            field=models.CharField(default='评论', max_length=40, verbose_name='评论区标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='digest_empty_text',
            field=models.CharField(default='暂无内容。', max_length=80, verbose_name='日报列表页空状态文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='digest_hint',
            field=models.CharField(default='每日 AI 新闻与关键信息速览', max_length=180, verbose_name='日报列表页说明'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='digest_title',
            field=models.CharField(default='AI 日报', max_length=80, verbose_name='日报列表页标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_left_text',
            field=models.CharField(default='© {year} DeepAI Blog', max_length=120, verbose_name='页脚左侧文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_right_text',
            field=models.CharField(default='Built with Django', max_length=120, verbose_name='页脚右侧文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_digest_empty_text',
            field=models.CharField(default='还没有发布日报。', max_length=80, verbose_name='首页日报区空状态文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_digest_more_text',
            field=models.CharField(default='查看全部', max_length=40, verbose_name='首页日报区“更多”文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_digest_title',
            field=models.CharField(default='最新日报', max_length=80, verbose_name='首页日报区标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_hero_subtitle',
            field=models.CharField(default='分享开发经验、产品实验和 AI 领域一线动态。', max_length=255, verbose_name='首页副标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_hero_title',
            field=models.CharField(default='个人技术博客 + AI 日报', max_length=255, verbose_name='首页主标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_posts_empty_text',
            field=models.CharField(default='还没有发布文章。', max_length=80, verbose_name='首页文章区空状态文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_posts_more_text',
            field=models.CharField(default='查看全部', max_length=40, verbose_name='首页文章区“更多”文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_posts_title',
            field=models.CharField(default='最新文章', max_length=80, verbose_name='首页文章区标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description_default',
            field=models.CharField(default='个人技术博客与 AI 日报', max_length=320, verbose_name='默认 Meta 描述'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_keywords_default',
            field=models.CharField(default='ai,blog,django', max_length=255, verbose_name='默认 Meta 关键词'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='posts_empty_text',
            field=models.CharField(default='暂无内容。', max_length=80, verbose_name='文章列表页空状态文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='posts_hint',
            field=models.CharField(default='技术实践、开发总结与项目复盘', max_length=180, verbose_name='文章列表页说明'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='posts_title',
            field=models.CharField(default='文章', max_length=80, verbose_name='文章列表页标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='profile_description',
            field=models.CharField(default='记录 AI、编程、自动化和个人产品实践。', max_length=255, verbose_name='侧栏简介'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='profile_name',
            field=models.CharField(default='Yuxia', max_length=80, verbose_name='侧栏昵称'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='profile_role',
            field=models.CharField(default='AI Engineer / Builder', max_length=120, verbose_name='侧栏角色'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='search_button_text',
            field=models.CharField(default='搜索', max_length=30, verbose_name='搜索按钮文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='search_empty_text',
            field=models.CharField(default='没有找到匹配内容。', max_length=80, verbose_name='搜索页空状态文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='search_hint',
            field=models.CharField(default='搜索任意文章内容', max_length=180, verbose_name='搜索页说明'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='search_placeholder',
            field=models.CharField(default='输入标题、摘要或正文关键词', max_length=120, verbose_name='搜索输入框占位文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='search_title',
            field=models.CharField(default='搜索', max_length=80, verbose_name='搜索页标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='DeepAI Blog', max_length=120, verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_tagline',
            field=models.CharField(default='个人技术博客与 AI 日报', max_length=180, verbose_name='站点副标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tags_empty_text',
            field=models.CharField(default='暂无标签。', max_length=80, verbose_name='标签页空状态文案'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tags_hint',
            field=models.CharField(default='按主题快速浏览内容', max_length=180, verbose_name='标签页说明'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tags_title',
            field=models.CharField(default='标签', max_length=80, verbose_name='标签页标题'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(max_length=40, verbose_name='社交文案'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='open_in_new_tab',
            field=models.BooleanField(default=True, verbose_name='新窗口打开'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(max_length=255, verbose_name='社交链接'),
        ),
    ]
